'use strict';
const API='https://tjjtemvclcgqmuhlnumr.supabase.co/functions/v1/haema-quiz';
const $=s=>document.querySelector(s), app=$('#app');
let weeks=[],weekIndex=0,currentSet=null,questions=[],index=0,answers={},selected=null,adminToken='',adminRows=[],deleteId=null,busy=false,view='home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sourceLink(s){try{const u=new URL(s.url);if(u.protocol!=='https:')return esc(s.title);return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`;}catch{return esc(s.title);}}
async function api(action,{method='GET',body,id,admin=false}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(API+'?action='+action+(id?'&id='+encodeURIComponent(id):''),{method,headers:{'Content-Type':'application/json',...(admin?{'x-quiz-session':adminToken}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const data=await r.json();if(!r.ok){if(r.status===401&&admin)adminToken='';throw new Error(data.error||'Anfrage fehlgeschlagen.');}return data;}finally{clearTimeout(timer);}}
function message(e){return e.name==='AbortError'?'Die Verbindung dauert zu lange. Bitte erneut versuchen.':e.message||'Verbindung fehlgeschlagen.';}
function errorBox(e,retry){app.innerHTML=`<div class="empty"><h2>Gerade nicht erreichbar</h2><p class="error">${esc(message(e))}</p><button id="retry">Erneut versuchen</button></div>`;$('#retry').onclick=retry;}
function focusHeading(){const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'smooth'});}
async function loadHome(){view='home';app.innerHTML='<p>Quizrunden werden geladen …</p>';try{weeks=await api('weeks');weekIndex=Math.min(weekIndex,Math.max(0,weeks.length-1));home();}catch(e){errorBox(e,loadHome);}}
function home(){view='home';if(!weeks.length){app.innerHTML='<div class="empty"><h1>Die erste Runde kommt bald.</h1><p>Hier erscheinen wöchentlich drei Sets mit je fünf Fragen.</p></div>';return;}const w=weeks[weekIndex];app.innerHTML=`<section class="intro"><div><div class="eyebrow">Deine wöchentliche Quizrunde</div><h1>Wissen prüfen.<br>Zusammenhänge verstehen.</h1><p>Allo-Tx, CAR-T und Hämatologie. Wähle ein Set und überprüfe deine Antworten direkt an der Literatur.</p></div><label class="week-picker">Ausgabe<select id="weekSelect">${weeks.map((x,i)=>`<option value="${i}" ${i===weekIndex?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label></section><section class="grid">${w.sets.map(s=>`<article class="set-card"><div class="set-no">SET ${String(s.position).padStart(2,'0')}</div><h2>${esc(s.title)}</h2><p>${s.count} Fragen · etwa ${s.count} Minuten${s.count<5?' · redaktionell gekürzt':''}</p><button data-set="${esc(s.id)}" ${s.count===0?'disabled':''}>${s.count?'Set starten':'Keine aktiven Fragen'}</button></article>`).join('')}</section><div class="rule"><div><strong>Eine beste Antwort</strong>Vier Optionen pro Frage</div><div><strong>Begründete Auflösung</strong>Auch für die anderen Optionen</div><div><strong>Direkt zur Literatur</strong>Quellen nach jeder Antwort</div></div>`;$('#weekSelect').onchange=e=>{weekIndex=Number(e.target.value);home();};app.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>startSet(b.dataset.set));}
async function startSet(id){currentSet=weeks.flatMap(w=>w.sets).find(s=>s.id===id);app.innerHTML='<p>Set wird geladen …</p>';try{questions=await api('set',{id});index=0;answers={};selected=null;if(!questions.length){await loadHome();return;}renderQuestion();focusHeading();}catch(e){errorBox(e,()=>startSet(id));}}
function renderQuestion(){view='quiz';selected=answers[questions[index].id]?.value||null;const q=questions[index],a=answers[q.id];app.innerHTML=`<div class="quiz-layout"><div class="quiz-top"><button class="quiet" id="backHome">← Wochenübersicht</button><p>${esc(currentSet.title)}<br>Frage ${index+1} von ${questions.length}</p></div><div class="progress" aria-label="Frage ${index+1} von ${questions.length}">${questions.map((x,i)=>`<span class="${answers[x.id]?'done':i===index?'current':''}"></span>`).join('')}</div><article class="question-card"><div class="question-meta"><span class="pill">${esc(q.topic)}</span><span>Quellen geprüft: ${esc(q.reviewed_at)}</span></div><h1>${esc(q.question)}</h1><div class="options" role="group" aria-label="Antwortoptionen">${q.options.map(o=>`<button class="option ${a?(o.value===a.correct?'correct':o.value===a.value?'wrong':''):''}" data-value="${o.value}" ${a?'disabled':''} aria-pressed="${o.value===selected}"><span class="letter">${o.value}</span><span>${esc(o.label)}${a?`<span class="feedback-small">${o.value===a.correct?'Richtige Antwort. ':o.value===a.value?'Deine Auswahl. ':''}${esc(a.options.find(x=>x.value===o.value).feedback)}</span>`:''}</span></button>`).join('')}</div>${!a?`<details><summary>Hinweis anzeigen</summary><p>${esc(q.hint)}</p></details>`:''}<div id="questionError" role="alert"></div>${a?`<section class="result-panel"><h3>${a.isCorrect?'Richtig beantwortet':'Noch etwas zum Mitnehmen'}</h3><p>${esc(a.explanation)}</p><div class="source-title">Literatur zur Auflösung</div><ul>${a.sources.map(s=>`<li>${sourceLink(s)}</li>`).join('')}</ul></section>`:''}<div class="actions">${index>0?'<button class="quiet" id="prev">Zurück</button>':''}${a?`<button id="next">${index===questions.length-1?'Ergebnis ansehen':'Nächste Frage →'}</button>`:'<button id="check" disabled>Antwort prüfen</button>'}</div></article></div>`;
$('#backHome').onclick=()=>{if(Object.keys(answers).length===questions.length||confirm('Zur Wochenübersicht wechseln? Diese Runde wird dabei beendet.'))home();};
app.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{selected=b.dataset.value;app.querySelectorAll('[data-value]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#check').disabled=false;});
if($('#check'))$('#check').onclick=checkAnswer;if($('#prev'))$('#prev').onclick=()=>{index--;renderQuestion();focusHeading();};if($('#next'))$('#next').onclick=()=>{if(index===questions.length-1){renderResult();}else{index++;renderQuestion();}focusHeading();};}
async function checkAnswer(){if(busy||!selected)return;busy=true;const value=selected,id=questions[index].id;$('#check').disabled=true;$('#check').textContent='Wird geprüft …';app.querySelectorAll('[data-value]').forEach(b=>b.disabled=true);try{const result=await api('answer',{method:'POST',body:{id,value}});answers[id]={...result,value};renderQuestion();}catch(e){$('#questionError').innerHTML=`<p class="error">${esc(message(e))}</p>`;$('#check').disabled=false;$('#check').textContent='Erneut prüfen';app.querySelectorAll('[data-value]').forEach(b=>b.disabled=false);}finally{busy=false;}}
function renderResult(){view='result';const score=questions.filter(q=>answers[q.id]?.isCorrect).length;app.innerHTML=`<div class="quiz-layout"><div class="eyebrow">${esc(currentSet.title)}</div><h1>Runde abgeschlossen.</h1><div class="score">${score}<span style="color:#8998aa"> / ${questions.length}</span></div><p>Die Auflösungen bleiben in dieser Runde zum Nachlesen verfügbar.</p><div class="actions"><button class="quiet" id="repeat">Set wiederholen</button><button id="finish">Zur Wochenübersicht</button></div>${questions.map((q,i)=>`<div class="review-row"><span class="status ${answers[q.id]?.isCorrect?'':'miss'}">${answers[q.id]?.isCorrect?'Richtig':'Zum Wiederholen'} · FRAGE ${i+1}</span><p>${esc(q.question)}</p><button class="quiet" data-review="${i}">Auflösung ansehen</button></div>`).join('')}</div>`;$('#finish').onclick=loadHome;$('#repeat').onclick=()=>startSet(currentSet.id);app.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.review);renderQuestion();focusHeading();});}
$('#adminOpen').onclick=()=>{if(adminToken)loadAdmin();else{$('#loginError').textContent='';$('#loginDialog').showModal();$('#password').focus();}};$('#cancelLogin').onclick=()=>$('#loginDialog').close();$('#loginDialog').addEventListener('close',()=>{$('#password').value='';});
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{const r=await api('login',{method:'POST',body:{password:$('#password').value}});adminToken=r.token;$('#loginDialog').close();await loadAdmin();}catch(e){$('#loginError').textContent=message(e);}finally{b.disabled=false;}};
async function loadAdmin(){view='admin';app.innerHTML='<p>Administration wird geladen …</p>';try{adminRows=await api('admin',{admin:true});renderAdmin();}catch(e){errorBox(e,()=>adminToken?loadAdmin():loadHome());}}
function renderAdmin(){view='admin';app.innerHTML=`<div class="intro"><div><div class="eyebrow">Administration</div><h1>Fragen verwalten</h1><p>${adminRows.length} aktive Fragen. Gelöschte Fragen werden nicht erneut importiert.</p></div><div class="actions"><button class="quiet" id="leaveAdmin">Zum Quiz</button><button class="quiet" id="logout">Abmelden</button></div></div><label class="week-picker">Ausgabe<select id="adminWeek"><option value="all">Alle Ausgaben</option>${weeks.map(w=>`<option value="${esc(w.id)}">${esc(w.title)}</option>`).join('')}</select></label><div id="adminList"></div>`;$('#leaveAdmin').onclick=loadHome;$('#logout').onclick=async()=>{try{await api('logout',{method:'POST',admin:true});adminToken='';loadHome();}catch(e){alert(message(e));}};$('#adminWeek').onchange=renderAdminList;renderAdminList();}
function renderAdminList(){const filter=$('#adminWeek').value;const rows=adminRows.filter(q=>filter==='all'||q.id.startsWith(filter));$('#adminList').innerHTML=rows.length?rows.map(q=>`<article class="admin-row"><div><small>${esc(q.id)} · ${esc(q.payload.topic)}</small><p>${esc(q.payload.question)}</p></div><button class="quiet" data-delete="${esc(q.id)}">Löschen</button></article>`).join(''):'<div class="empty">Keine aktiven Fragen in dieser Ausgabe.</div>';app.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{deleteId=b.dataset.delete;$('#deleteText').textContent=adminRows.find(q=>q.id===deleteId).payload.question;$('#deleteError').textContent='';$('#deleteDialog').showModal();});}
$('#cancelDelete').onclick=()=>$('#deleteDialog').close();$('#confirmDelete').onclick=async()=>{const b=$('#confirmDelete');b.disabled=true;try{await api('question',{method:'DELETE',id:deleteId,admin:true});adminRows=adminRows.filter(q=>q.id!==deleteId);$('#deleteDialog').close();renderAdmin();}catch(e){$('#deleteError').textContent=message(e);}finally{b.disabled=false;}};
document.querySelector('.brand').onclick=e=>{e.preventDefault();if(view!=='quiz'||confirm('Diese Runde beenden und zur Wochenübersicht wechseln?'))loadHome();};loadHome();
